#!/usr/bin/env python


import rospy
import actionlib
from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal
from geometry_msgs.msg import PoseStamped
# import tf
# from sensor_msgs.msg import LaserScan
# from tf.transformations import euler_from_quaternion


def movebase_client():

    client = actionlib.SimpleActionClient('/leader/move_base',MoveBaseAction)
    client.wait_for_server()

    goal = MoveBaseGoal()
    goal.target_pose.header.frame_id = "map"
    goal.target_pose.header.stamp = rospy.Time.now()
    # goal.target_pose.pose.position.x = 8.56
    # goal.target_pose.pose.position.y = 1.27
    goal.target_pose.pose.position.x = -7
    goal.target_pose.pose.position.y = 3
    goal.target_pose.pose.orientation.w = 1.0

    client.send_goal(goal)
    wait = client.wait_for_result()
    if not wait:
        rospy.logerr("Action server not available!")
        rospy.signal_shutdown("Action server not available!")
    else:
        return client.get_result()


def publish_on_move_base():
    # Create a publisher
    pub = rospy.Publisher("/leader/move_base_simple/goal", PoseStamped, queue_size=10)
    # Create a message of type PoseStamped
    message = PoseStamped()
    # Build your message
    message.header.frame_id = "map"
    message.header.stamp = rospy.Time.now()
    message.pose.position.x = -7
    message.pose.position.y = 3
    message.pose.position.z = 0
    message.pose.orientation.w = 1

    rate = rospy.Rate(1)

    while not rospy.is_shutdown():
        pub.publish(message)
        rate.sleep()


# if __name__ == '__main__':
    # try:
    #     rospy.init_node('movebase_client_py')
    #     result = movebase_client()
    #     if result:
    #         rospy.loginfo("Goal execution done!")
    # except rospy.ROSInterruptException:
    #     rospy.loginfo("Navigation test finished.")


if __name__ == '__main__':
    rospy.init_node('movebase_client_py')
    publish_on_move_base()
